import { getLocale } from '../i18n';

const en = {
  title: 'Administration',
  subtitle: 'Users, access and server-owned data',
  createUser: 'Create user',
  localProvisioningOff: 'Local account provisioning is off on this server. Accounts come from the identity provider and appear under Pending SSO for administrator approval; passwords, activation links and credential resets are unavailable.',
  users: 'Users',
  defaultPlaylists: 'Default playlists',
  pendingSso: 'Pending SSO',
  sharedDownloads: 'Shared downloads',
  never: 'Never',
  operationFailed: 'The operation failed',
  errorRejected: 'The server rejected this change.',
  errorLastAdmin: 'This is the last administrator managed on this server. Keep one active administrator.',
  errorNotFound: 'That item no longer exists.',
  errorUsernameTaken: 'That username is already taken.',
  errorUnknownPlaylist: 'That playlist no longer exists. Refresh and try again.',
  errorForbidden: 'You are not allowed to do that.',
  errorUnauthenticated: 'Your session has expired. Sign in again.',
  errorCsrf: 'The request was rejected for security reasons. Reload the page and try again.',
  errorRateLimited: 'Too many attempts. Wait a moment and try again.',
  errorTooLarge: 'The request was too large.',
  errorServer: 'The server could not complete this operation.',
  noUsers: 'No users',
  noUsersBody: 'Create an account to grant access to this server.',
  noAssignedPlaylists: 'No assigned playlists',
  allPlaylists: 'All playlists',
  playlistNumber: 'Playlist {id}',
  userCreated: 'User created',
  activationOnce: 'This activation link is shown once. Send it securely to the user.',
  createLocalUser: 'Create local user',
  cancel: 'Cancel',
  creating: 'Creating…',
  create: 'Create',
  username: 'Username',
  displayName: 'Display name',
  role: 'Role',
  user: 'User',
  administrator: 'Administrator',
  invitedHelp: 'The account starts invited. The user chooses their password and MFA during activation.',
  userSaved: 'User saved',
  accessSaved: 'Playlist access saved',
  noAuth: 'No authentication enrolled',
  lastLogin: 'Last login: {date}',
  profile: 'Profile',
  playlists: 'Playlists',
  sessions: 'Sessions',
  progress: 'Progress',
  manualRole: 'Manual role',
  status: 'Status',
  invited: 'Invited',
  pending: 'Pending',
  credentials: 'Credentials',
  setPassword: 'Set a password now',
  sendActivation: 'Send an activation link',
  credentialsHelp: 'A password makes the account usable immediately. An activation link lets the person choose their own, and expires in 24 hours.',
  passwordHint: 'Use at least 12 characters.',
  userCreatedActive: 'Account created and ready to use.',
  statusHelp: 'Invited and Pending are set by the system, not chosen here.',
  selfGuardHelp: 'You cannot demote, disable or delete your own account. Another administrator can.',
  contentGone: 'Content no longer in the catalog',
  errorLocalProvisioningDisabled: 'Local account provisioning is off on this server. Approve the pending identity from the identity provider instead.',
  errorPasswordAuthDisabled: 'Password sign-in is off on this server, so this request cannot set a password.',
  errorStatusNotSettable: 'That status is set by the server, not chosen here. An account can be made Active or Disabled.',
  active: 'Active',
  disabled: 'Disabled',
  effectiveRoleHelp: 'Effective role: {role}. Changing role or status revokes this user’s sessions.',
  saveChanges: 'Save changes',
  selfChangeTitle: 'Change your own account?',
  selfChangeBody: 'This signs you out of every device, and lowering your own role or status removes your administrator access.',
  resetCredentials: 'Reset password and MFA',
  deleteUser: 'Delete user',
  removeAccessHelp: 'Removing access immediately stops this user’s streams and suspends their downloads for that playlist.',
  adminAccessHelp: 'Administrators already see every playlist. Grants only apply to users.',
  saveAccess: 'Save playlist access',
  allSessionsRevoked: 'All sessions revoked',
  deleteUserTitle: 'Delete user permanently?',
  deleteUserBody: 'The account, sessions, activity, private download associations and linked identities will be permanently deleted.',
  deleteSelfBody: 'This is your own account: you will be signed out immediately and will not be able to sign in again.',
  resetTitle: 'Reset password and MFA?',
  resetBody: 'The password and every second factor are deleted, all sessions end, and a one-time setup link is issued.',
  resetSelfBody: 'This is your own account: only the setup link will let you sign in again.',
  credentialsReset: 'Credentials reset',
  resetOnce: 'All sessions and streams were terminated. This setup link is shown once.',
  revokeAllSessions: 'Revoke all sessions',
  revokeAllTitle: 'Revoke every session?',
  revokeAllBody: 'Every device signed in to this account is signed out.',
  revokeAllSelfBody: 'This includes the session you are using right now.',
  currentSession: 'This session',
  you: 'You',
  noActiveSessions: 'No active sessions.',
  lastSeen: '{method} · Last seen {date}',
  expires: 'Expires {date}',
  revoke: 'Revoke',
  noResume: 'No resume history.',
  progressMinutes: '{position} of {duration} minutes',
  updated: 'Updated {date}',
  remove: 'Remove',
  templateTitle: 'Default playlist template',
  templateHelp: 'These playlists are copied as explicit access grants when a future account is activated or provisioned. Updating this template never changes existing users.',
  templateSaved: 'Default playlist template saved',
  saveTemplate: 'Save template',
  noPlaylists: 'No playlists are configured.',
  playlistItems: '{count} items · {mode}',
  noPendingSso: 'No pending SSO identities',
  noPendingSsoBody: 'Unknown OIDC identities awaiting approval will appear here.',
  oidcLinked: 'SSO identity linked',
  oidcProvisioned: 'SSO user provisioned',
  unnamedIdentity: 'Unnamed identity',
  groups: 'Groups: {groups}',
  noGroups: 'No groups reported',
  adminGroup: 'ADMIN GROUP',
  approvalTarget: 'Approval target',
  createNewUser: 'Create a new user',
  linkTo: 'Link to {name} (@{username})',
  approving: 'Approving…',
  linkIdentity: 'Link identity',
  createApprove: 'Create and approve',
  noDownloads: 'No server downloads',
  noDownloadsBody: 'Shared transfer blobs will appear here.',
  activeRequest: '{count} active request',
  activeRequests: '{count} active requests',
  affectedUser: '{count} affected user',
  affectedUsers: '{count} affected users',
  suspendedRequest: '{count} suspended',
  suspendedRequests: '{count} suspended',
  cancelBlob: 'Cancel shared blob',
  cancelDownloadTitle: 'Cancel shared download?',
  cancelDownloadBody: 'This removes the shared transfer for {count} request(s). Affected user IDs: {ids}.',
  cancelEveryone: 'Cancel for everyone',
  downloadCancelled: 'Download cancelled for {count} user(s)',
  savedToken: 'I saved it',
  copied: '{label} copied',
  copyFailed: 'Could not copy automatically',
  token: 'Token',
  copyLink: 'Copy link',
  copyToken: 'Copy token',
  password: 'Password',
  oidc: 'Single sign-on',
  totp: 'Authenticator app',
  webauthn: 'Security key',
  clientBrowser: 'Browser',
  clientLinked: 'Linked device',
  clientNative: 'App',
  modeXtream: 'Xtream',
  modeUrl: 'Remote URL',
  modeFile: 'Uploaded file',
  downloadQueued: 'Queued',
  downloadRunning: 'Running',
  downloadDone: 'Completed',
  downloadFailed: 'Failed',
  downloadCancelledStatus: 'Cancelled',
  downloadPaused: 'Paused',
  downloadUnknown: 'Unknown',
  adminShort: 'Admin',
  searchUsers: 'Search users',
  filterAll: 'All',
  noMatches: 'No matching users',
  noMatchesBody: 'Try another name, or clear the status filter.',
  created: 'Created {date}',
  accountSection: 'Account',
  accessSection: 'Playlist access',
  sessionsHelp: 'Devices currently signed in to this account.',
  progressHelp: 'Playback positions stored for this account.',
  dangerZone: 'Danger zone',
  dangerZoneHelp: 'Resetting issues a new activation link and ends every session.',
  oidcHelp: 'Approve an unknown single sign-on identity, or link it to an existing account.',
  downloadsHelp: 'Transfers stored once on the server and shared by every requester.',
  seenAt: 'Seen {date}',
  tokenLink: 'Activation link',
} as const;

export type AdminTextKey = keyof typeof en;

const fr: Record<AdminTextKey, string> = {
  title: 'Administration',
  subtitle: 'Utilisateurs, accès et données du serveur',
  createUser: 'Créer un utilisateur',
  localProvisioningOff: "Le provisionnement de comptes locaux est désactivé sur ce serveur. Les comptes proviennent du fournisseur d’identité et apparaissent dans « SSO en attente » pour être approuvés par un administrateur ; les mots de passe, les liens d’activation et la réinitialisation des identifiants ne sont pas disponibles.",
  users: 'Utilisateurs',
  defaultPlaylists: 'Playlists par défaut',
  pendingSso: 'SSO en attente',
  sharedDownloads: 'Téléchargements partagés',
  never: 'Jamais',
  operationFailed: "L'opération a échoué",
  errorRejected: 'Le serveur a refusé cette modification.',
  errorLastAdmin: 'Il ne reste qu’un seul administrateur géré sur ce serveur. Gardez toujours un administrateur actif.',
  errorNotFound: "Cet élément n'existe plus.",
  errorUsernameTaken: "Ce nom d'utilisateur est déjà pris.",
  errorUnknownPlaylist: "Cette playlist n'existe plus. Actualisez, puis réessayez.",
  errorForbidden: "Vous n'avez pas le droit d'effectuer cette action.",
  errorUnauthenticated: 'Votre session a expiré. Reconnectez-vous.',
  errorCsrf: 'La requête a été refusée pour des raisons de sécurité. Rechargez la page et réessayez.',
  errorRateLimited: 'Trop de tentatives. Patientez un instant puis réessayez.',
  errorTooLarge: 'La requête était trop volumineuse.',
  errorServer: "Le serveur n'a pas pu terminer cette opération.",
  noUsers: 'Aucun utilisateur',
  noUsersBody: 'Créez un compte pour lui donner accès à ce serveur.',
  noAssignedPlaylists: 'Aucune playlist attribuée',
  allPlaylists: 'Toutes les playlists',
  playlistNumber: 'Playlist {id}',
  userCreated: 'Utilisateur créé',
  activationOnce: "Ce lien d'activation n'est affiché qu'une fois. Envoyez-le à l'utilisateur de manière sécurisée.",
  createLocalUser: 'Créer un utilisateur local',
  cancel: 'Annuler',
  creating: 'Création…',
  create: 'Créer',
  username: "Nom d'utilisateur",
  displayName: 'Nom affiché',
  role: 'Rôle',
  user: 'Utilisateur',
  administrator: 'Administrateur',
  invitedHelp: "Le compte commence avec le statut invité. L'utilisateur choisit son mot de passe et son MFA pendant l'activation.",
  userSaved: 'Utilisateur enregistré',
  accessSaved: 'Accès aux playlists enregistré',
  noAuth: "Aucune méthode d'authentification configurée",
  lastLogin: 'Dernière connexion : {date}',
  profile: 'Profil',
  playlists: 'Playlists',
  sessions: 'Sessions',
  progress: 'Progression',
  manualRole: 'Rôle manuel',
  status: 'Statut',
  invited: 'Invité',
  pending: 'En attente',
  credentials: 'Identifiants',
  setPassword: 'Définir un mot de passe',
  sendActivation: "Envoyer un lien d'activation",
  credentialsHelp: "Un mot de passe rend le compte utilisable immédiatement. Un lien d'activation laisse la personne choisir le sien et expire sous 24 heures.",
  passwordHint: 'Au moins 12 caractères.',
  userCreatedActive: 'Compte créé et prêt à utiliser.',
  statusHelp: "« Invité » et « En attente » sont définis par le système, pas choisis ici.",
  selfGuardHelp: "Vous ne pouvez ni rétrograder, ni désactiver, ni supprimer votre propre compte. Un autre administrateur le peut.",
  contentGone: 'Contenu absent du catalogue',
  errorLocalProvisioningDisabled: "Le provisionnement de comptes locaux est désactivé sur ce serveur. Approuvez plutôt l’identité en attente provenant du fournisseur d’identité.",
  errorPasswordAuthDisabled: "La connexion par mot de passe est désactivée sur ce serveur ; cette requête ne peut donc pas définir de mot de passe.",
  errorStatusNotSettable: "Ce statut est défini par le serveur, pas choisi ici. Un compte peut être Actif ou Désactivé.",
  active: 'Actif',
  disabled: 'Désactivé',
  effectiveRoleHelp: "Rôle effectif : {role}. Modifier le rôle ou le statut révoque les sessions de l'utilisateur.",
  saveChanges: 'Enregistrer',
  selfChangeTitle: 'Modifier votre propre compte ?',
  selfChangeBody: 'Vous serez déconnecté de tous vos appareils, et abaisser votre rôle ou votre statut vous retire vos droits d’administrateur.',
  resetCredentials: 'Réinitialiser le mot de passe et le MFA',
  deleteUser: "Supprimer l'utilisateur",
  removeAccessHelp: "Retirer l'accès arrête immédiatement les flux de cet utilisateur et suspend ses téléchargements pour cette playlist.",
  adminAccessHelp: 'Les administrateurs voient déjà toutes les playlists. Les attributions ne concernent que les utilisateurs.',
  saveAccess: "Enregistrer l'accès aux playlists",
  allSessionsRevoked: 'Toutes les sessions ont été révoquées',
  deleteUserTitle: "Supprimer définitivement l'utilisateur ?",
  deleteUserBody: 'Le compte, ses sessions, son activité, ses téléchargements privés et ses identités associées seront définitivement supprimés.',
  deleteSelfBody: 'Il s’agit de votre propre compte : vous serez déconnecté immédiatement et ne pourrez plus vous reconnecter.',
  resetTitle: 'Réinitialiser le mot de passe et le MFA ?',
  resetBody: 'Le mot de passe et tous les seconds facteurs sont supprimés, toutes les sessions prennent fin et un lien de configuration à usage unique est émis.',
  resetSelfBody: 'Il s’agit de votre propre compte : seul le lien de configuration vous permettra de vous reconnecter.',
  credentialsReset: 'Identifiants réinitialisés',
  resetOnce: "Toutes les sessions et tous les flux ont été arrêtés. Ce lien de configuration n'est affiché qu'une fois.",
  revokeAllSessions: 'Révoquer toutes les sessions',
  revokeAllTitle: 'Révoquer toutes les sessions ?',
  revokeAllBody: 'Tous les appareils connectés à ce compte seront déconnectés.',
  revokeAllSelfBody: 'Cela inclut la session que vous utilisez en ce moment.',
  currentSession: 'Cette session',
  you: 'Vous',
  noActiveSessions: 'Aucune session active.',
  lastSeen: '{method} · Dernière activité {date}',
  expires: 'Expire le {date}',
  revoke: 'Révoquer',
  noResume: 'Aucun historique de reprise.',
  progressMinutes: '{position} sur {duration} minutes',
  updated: 'Mis à jour le {date}',
  remove: 'Supprimer',
  templateTitle: 'Modèle de playlists par défaut',
  templateHelp: "Ces playlists sont copiées comme droits d'accès explicites lorsqu'un futur compte est activé ou provisionné. Modifier ce modèle ne change jamais les utilisateurs existants.",
  templateSaved: 'Modèle de playlists par défaut enregistré',
  saveTemplate: 'Enregistrer le modèle',
  noPlaylists: "Aucune playlist n'est configurée.",
  playlistItems: '{count} éléments · {mode}',
  noPendingSso: 'Aucune identité SSO en attente',
  noPendingSsoBody: "Les identités OIDC inconnues en attente d'approbation apparaîtront ici.",
  oidcLinked: 'Identité SSO associée',
  oidcProvisioned: 'Utilisateur SSO provisionné',
  unnamedIdentity: 'Identité sans nom',
  groups: 'Groupes : {groups}',
  noGroups: 'Aucun groupe indiqué',
  adminGroup: 'GROUPE ADMIN',
  approvalTarget: "Cible de l'approbation",
  createNewUser: 'Créer un nouvel utilisateur',
  linkTo: 'Associer à {name} (@{username})',
  approving: 'Approbation…',
  linkIdentity: "Associer l'identité",
  createApprove: 'Créer et approuver',
  noDownloads: 'Aucun téléchargement serveur',
  noDownloadsBody: 'Les transferts partagés apparaîtront ici.',
  activeRequest: '{count} demande active',
  activeRequests: '{count} demandes actives',
  affectedUser: '{count} utilisateur concerné',
  affectedUsers: '{count} utilisateurs concernés',
  suspendedRequest: '{count} suspendue',
  suspendedRequests: '{count} suspendues',
  cancelBlob: 'Annuler le transfert partagé',
  cancelDownloadTitle: 'Annuler le téléchargement partagé ?',
  cancelDownloadBody: 'Cette action supprime le transfert partagé pour {count} demande(s). Identifiants des utilisateurs concernés : {ids}.',
  cancelEveryone: 'Annuler pour tout le monde',
  downloadCancelled: 'Téléchargement annulé pour {count} utilisateur(s)',
  savedToken: "Je l'ai enregistré",
  copied: '{label} copié',
  copyFailed: 'Impossible de copier automatiquement',
  token: 'Jeton',
  copyLink: 'Copier le lien',
  copyToken: 'Copier le jeton',
  password: 'Mot de passe',
  oidc: 'Authentification unique',
  totp: "Application d'authentification",
  webauthn: 'Clé de sécurité',
  clientBrowser: 'Navigateur',
  clientLinked: 'Appareil associé',
  clientNative: 'Application',
  modeXtream: 'Xtream',
  modeUrl: 'URL distante',
  modeFile: 'Fichier importé',
  downloadQueued: "En attente",
  downloadRunning: 'En cours',
  downloadDone: 'Terminé',
  downloadFailed: 'Échec',
  downloadCancelledStatus: 'Annulé',
  downloadPaused: 'En pause',
  downloadUnknown: 'Inconnu',
  adminShort: 'Admin',
  searchUsers: 'Rechercher un utilisateur',
  filterAll: 'Tous',
  noMatches: 'Aucun utilisateur correspondant',
  noMatchesBody: 'Essayez un autre nom ou retirez le filtre de statut.',
  created: 'Créé le {date}',
  accountSection: 'Compte',
  accessSection: 'Accès aux playlists',
  sessionsHelp: 'Appareils actuellement connectés à ce compte.',
  progressHelp: 'Positions de lecture enregistrées pour ce compte.',
  dangerZone: 'Zone sensible',
  dangerZoneHelp: "La réinitialisation crée un nouveau lien d'activation et met fin à toutes les sessions.",
  oidcHelp: "Approuvez une identité d'authentification unique inconnue, ou associez-la à un compte existant.",
  downloadsHelp: 'Transferts stockés une seule fois sur le serveur et partagés par tous les demandeurs.',
  seenAt: 'Vue le {date}',
  tokenLink: "Lien d'activation",
};

export function adminText(key: AdminTextKey, values: Record<string, string | number> = {}): string {
  const template = (getLocale() === 'fr' ? fr : en)[key];
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

export const adminLocale = () => getLocale() === 'fr' ? 'fr' : 'en';
