import { getLocale } from '../i18n';

const en = {
  title: 'Administration',
  subtitle: 'Users, access and server-owned data',
  createUser: 'Create user',
  users: 'Users',
  defaultPlaylists: 'Default playlists',
  pendingSso: 'Pending SSO',
  sharedDownloads: 'Shared downloads',
  never: 'Never',
  operationFailed: 'The operation failed',
  noUsers: 'No users',
  noUsersBody: 'Create an account to grant access to this server.',
  noAssignedPlaylists: 'No assigned playlists',
  playlistNumber: 'Playlist {id}',
  userCreated: 'User created',
  activationOnce: 'This activation link is shown once. Send it securely to the user.',
  createLocalUser: 'Create local user',
  cancel: 'Cancel',
  creating: 'Creating…',
  create: 'Create',
  username: 'Username',
  displayName: 'Display name',
  role: 'Role',
  user: 'User',
  administrator: 'Administrator',
  invitedHelp: 'The account starts invited. The user chooses their password and MFA during activation.',
  userSaved: 'User saved',
  accessSaved: 'Playlist access saved',
  noAuth: 'No authentication enrolled',
  lastLogin: 'Last login: {date}',
  profile: 'Profile',
  playlists: 'Playlists',
  sessions: 'Sessions',
  progress: 'Progress',
  manualRole: 'Manual role',
  status: 'Status',
  invited: 'Invited',
  pending: 'Pending',
  active: 'Active',
  disabled: 'Disabled',
  effectiveRoleHelp: 'Effective role: {role}. Changing role or status revokes this user’s sessions.',
  saveChanges: 'Save changes',
  resetCredentials: 'Reset password and MFA',
  deleteUser: 'Delete user',
  removeAccessHelp: 'Removing access immediately stops this user’s streams and suspends their downloads for that playlist.',
  saveAccess: 'Save playlist access',
  allSessionsRevoked: 'All sessions revoked',
  deleteUserTitle: 'Delete user permanently?',
  deleteUserBody: 'The account, sessions, activity, private download associations and linked identities will be permanently deleted.',
  credentialsReset: 'Credentials reset',
  resetOnce: 'All sessions and streams were terminated. This setup link is shown once.',
  revokeAllSessions: 'Revoke all sessions',
  noActiveSessions: 'No active sessions.',
  lastSeen: '{method} · Last seen {date}',
  expires: 'Expires {date}',
  revoke: 'Revoke',
  noResume: 'No resume history.',
  progressMinutes: '{position} of {duration} minutes',
  updated: 'Updated {date}',
  remove: 'Remove',
  templateTitle: 'Default playlist template',
  templateHelp: 'These playlists are copied as explicit access grants when a future account is activated or provisioned. Updating this template never changes existing users.',
  templateSaved: 'Default playlist template saved',
  saveTemplate: 'Save template',
  noPlaylists: 'No playlists are configured.',
  playlistItems: '{count} items · {mode}',
  noPendingSso: 'No pending SSO identities',
  noPendingSsoBody: 'Unknown OIDC identities awaiting approval will appear here.',
  oidcLinked: 'SSO identity linked',
  oidcProvisioned: 'SSO user provisioned',
  unnamedIdentity: 'Unnamed identity',
  groups: 'Groups: {groups}',
  noGroups: 'No groups reported',
  adminGroup: 'ADMIN GROUP',
  approvalTarget: 'Approval target',
  createNewUser: 'Create a new user',
  linkTo: 'Link to {name} (@{username})',
  approving: 'Approving…',
  linkIdentity: 'Link identity',
  createApprove: 'Create and approve',
  noDownloads: 'No server downloads',
  noDownloadsBody: 'Shared transfer blobs will appear here.',
  activeRequest: '{count} active request',
  activeRequests: '{count} active requests',
  affectedUser: '{count} affected user',
  affectedUsers: '{count} affected users',
  cancelBlob: 'Cancel shared blob',
  cancelDownloadTitle: 'Cancel shared download?',
  cancelDownloadBody: 'This removes the shared transfer for {count} request(s). Affected user IDs: {ids}.',
  cancelEveryone: 'Cancel for everyone',
  downloadCancelled: 'Download cancelled for {count} user(s)',
  savedToken: 'I saved it',
  copied: '{label} copied',
  copyFailed: 'Could not copy automatically',
  activationLink: 'Activation link',
  token: 'Token',
  copyLink: 'Copy link',
  copyToken: 'Copy token',
  password: 'Password',
  oidc: 'Single sign-on',
  recovery: 'Recovery code',
  webauthn: 'Security key',
  clientBrowser: 'Browser',
  modeXtream: 'Xtream',
  modeUrl: 'Remote URL',
  modeFile: 'Uploaded file',
  downloadQueued: 'Queued',
  downloadRunning: 'Running',
  downloadDone: 'Completed',
  downloadFailed: 'Failed',
  downloadCancelledStatus: 'Cancelled',
  downloadPaused: 'Paused',
  downloadUnknown: 'Unknown',
} as const;

export type AdminTextKey = keyof typeof en;

const fr: Record<AdminTextKey, string> = {
  title: 'Administration',
  subtitle: 'Utilisateurs, accès et données du serveur',
  createUser: 'Créer un utilisateur',
  users: 'Utilisateurs',
  defaultPlaylists: 'Playlists par défaut',
  pendingSso: 'SSO en attente',
  sharedDownloads: 'Téléchargements partagés',
  never: 'Jamais',
  operationFailed: "L'opération a échoué",
  noUsers: 'Aucun utilisateur',
  noUsersBody: 'Créez un compte pour lui donner accès à ce serveur.',
  noAssignedPlaylists: 'Aucune playlist attribuée',
  playlistNumber: 'Playlist {id}',
  userCreated: 'Utilisateur créé',
  activationOnce: "Ce lien d'activation n'est affiché qu'une fois. Envoyez-le à l'utilisateur de manière sécurisée.",
  createLocalUser: 'Créer un utilisateur local',
  cancel: 'Annuler',
  creating: 'Création…',
  create: 'Créer',
  username: "Nom d'utilisateur",
  displayName: 'Nom affiché',
  role: 'Rôle',
  user: 'Utilisateur',
  administrator: 'Administrateur',
  invitedHelp: "Le compte commence avec le statut invité. L'utilisateur choisit son mot de passe et son MFA pendant l'activation.",
  userSaved: 'Utilisateur enregistré',
  accessSaved: 'Accès aux playlists enregistré',
  noAuth: "Aucune méthode d'authentification configurée",
  lastLogin: 'Dernière connexion : {date}',
  profile: 'Profil',
  playlists: 'Playlists',
  sessions: 'Sessions',
  progress: 'Progression',
  manualRole: 'Rôle manuel',
  status: 'Statut',
  invited: 'Invité',
  pending: 'En attente',
  active: 'Actif',
  disabled: 'Désactivé',
  effectiveRoleHelp: "Rôle effectif : {role}. Modifier le rôle ou le statut révoque les sessions de l'utilisateur.",
  saveChanges: 'Enregistrer',
  resetCredentials: 'Réinitialiser le mot de passe et le MFA',
  deleteUser: "Supprimer l'utilisateur",
  removeAccessHelp: "Retirer l'accès arrête immédiatement les flux de cet utilisateur et suspend ses téléchargements pour cette playlist.",
  saveAccess: "Enregistrer l'accès aux playlists",
  allSessionsRevoked: 'Toutes les sessions ont été révoquées',
  deleteUserTitle: "Supprimer définitivement l'utilisateur ?",
  deleteUserBody: 'Le compte, ses sessions, son activité, ses téléchargements privés et ses identités associées seront définitivement supprimés.',
  credentialsReset: 'Identifiants réinitialisés',
  resetOnce: "Toutes les sessions et tous les flux ont été arrêtés. Ce lien de configuration n'est affiché qu'une fois.",
  revokeAllSessions: 'Révoquer toutes les sessions',
  noActiveSessions: 'Aucune session active.',
  lastSeen: '{method} · Dernière activité {date}',
  expires: 'Expire le {date}',
  revoke: 'Révoquer',
  noResume: 'Aucun historique de reprise.',
  progressMinutes: '{position} sur {duration} minutes',
  updated: 'Mis à jour le {date}',
  remove: 'Supprimer',
  templateTitle: 'Modèle de playlists par défaut',
  templateHelp: "Ces playlists sont copiées comme droits d'accès explicites lorsqu'un futur compte est activé ou provisionné. Modifier ce modèle ne change jamais les utilisateurs existants.",
  templateSaved: 'Modèle de playlists par défaut enregistré',
  saveTemplate: 'Enregistrer le modèle',
  noPlaylists: "Aucune playlist n'est configurée.",
  playlistItems: '{count} éléments · {mode}',
  noPendingSso: 'Aucune identité SSO en attente',
  noPendingSsoBody: "Les identités OIDC inconnues en attente d'approbation apparaîtront ici.",
  oidcLinked: 'Identité SSO associée',
  oidcProvisioned: 'Utilisateur SSO provisionné',
  unnamedIdentity: 'Identité sans nom',
  groups: 'Groupes : {groups}',
  noGroups: 'Aucun groupe indiqué',
  adminGroup: 'GROUPE ADMIN',
  approvalTarget: "Cible de l'approbation",
  createNewUser: 'Créer un nouvel utilisateur',
  linkTo: 'Associer à {name} (@{username})',
  approving: 'Approbation…',
  linkIdentity: "Associer l'identité",
  createApprove: 'Créer et approuver',
  noDownloads: 'Aucun téléchargement serveur',
  noDownloadsBody: 'Les transferts partagés apparaîtront ici.',
  activeRequest: '{count} demande active',
  activeRequests: '{count} demandes actives',
  affectedUser: '{count} utilisateur concerné',
  affectedUsers: '{count} utilisateurs concernés',
  cancelBlob: 'Annuler le transfert partagé',
  cancelDownloadTitle: 'Annuler le téléchargement partagé ?',
  cancelDownloadBody: 'Cette action supprime le transfert partagé pour {count} demande(s). Identifiants des utilisateurs concernés : {ids}.',
  cancelEveryone: 'Annuler pour tout le monde',
  downloadCancelled: 'Téléchargement annulé pour {count} utilisateur(s)',
  savedToken: "Je l'ai enregistré",
  copied: '{label} copié',
  copyFailed: 'Impossible de copier automatiquement',
  activationLink: "Lien d'activation",
  token: 'Jeton',
  copyLink: 'Copier le lien',
  copyToken: 'Copier le jeton',
  password: 'Mot de passe',
  oidc: 'Authentification unique',
  recovery: 'Code de récupération',
  webauthn: 'Clé de sécurité',
  clientBrowser: 'Navigateur',
  modeXtream: 'Xtream',
  modeUrl: 'URL distante',
  modeFile: 'Fichier importé',
  downloadQueued: "En attente",
  downloadRunning: 'En cours',
  downloadDone: 'Terminé',
  downloadFailed: 'Échec',
  downloadCancelledStatus: 'Annulé',
  downloadPaused: 'En pause',
  downloadUnknown: 'Inconnu',
};

export function adminText(key: AdminTextKey, values: Record<string, string | number> = {}): string {
  const template = (getLocale() === 'fr' ? fr : en)[key];
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

export const adminLocale = () => getLocale() === 'fr' ? 'fr' : 'en';
