import { getLocale } from '../i18n';

const en = {
  loginTitle: 'Sign in to OpenTV',
  username: 'Username',
  password: 'Password',
  signIn: 'Sign in',
  sso: 'Continue with single sign-on',
  noMethods: 'No sign-in method is configured. Contact the server administrator.',
  pending: 'Your single sign-on account is waiting for administrator approval.',
  oidcError: 'Single sign-on could not be completed. Please try again.',
  challengeInvalid: 'This authentication challenge expired or was already used. Start again.',
  rateLimited: 'Too many attempts. Wait a moment and try again.',
  setupTitle: 'Create the first administrator',
  setupToken: 'Bootstrap token',
  displayName: 'Display name',
  createAdmin: 'Create administrator',
  activateTitle: 'Activate your account',
  activationToken: 'Activation token',
  choosePassword: 'Choose password',
  passwordHint: 'Use at least 12 characters.',
  continue: 'Continue',
  totpTitle: 'Set up an authenticator app',
  totpBody: 'Scan this QR code, or enter the secret manually. Then type the six-digit code.',
  totpCode: '6-digit code',
  secret: 'Manual secret',
  verify: 'Verify',
  mfaTitle: 'Two-factor authentication',
  mfaBody: 'Complete a second step to finish signing in.',
  useAuthenticator: 'Use authenticator code',
  useSecurityKey: 'Use security key',
  useRecovery: 'Use recovery code',
  recoveryCode: 'Recovery code',
  securityKeyLabel: 'Security key name',
  securityKeyDefault: 'Security key',
  securityKeyUnavailable: 'Security keys are unavailable in this browser or insecure context.',
  securityKeyOptionsInvalid: 'The security-key options returned by the server are invalid.',
  securityKeyRegistrationCancelled: 'The security-key registration was cancelled.',
  securityKeyRequestCancelled: 'The security-key request was cancelled.',
  recentAuthRequired: 'Recent authentication is required.',
  securityTitle: 'Account security',
  securitySubtitle: 'Manage your password, security keys, recovery codes, and sessions.',
  changePassword: 'Change password',
  newPassword: 'New password',
  passwordChanged: 'Password changed.',
  addSecurityKey: 'Add a security key',
  securityKeyAdded: 'Security key added.',
  recoveryTitle: 'Save your recovery codes',
  recoveryBody: 'Each code can be used once. Store them somewhere safe; they will not be shown again.',
  regenerate: 'Generate new recovery codes',
  copy: 'Copy',
  download: 'Download',
  copied: 'Copied.',
  copyFailed: 'Could not copy the codes. Select and copy them manually.',
  downloadFailed: 'Could not download the codes. Select and save them manually.',
  savedCodes: 'I have saved these codes',
  currentLogout: 'Sign out of this session',
  allLogout: 'Sign out everywhere',
  cancelled: 'The browser cancelled the security-key request.',
  genericError: 'Something went wrong. Try again.',
  challengeMissing: 'The authentication challenge is invalid.',
  authIncomplete: 'Authentication has not completed.',
  serviceUnavailable: 'The authentication service is unavailable.',
  retry: 'Retry',
  backToLogin: 'Back to sign in',
} as const;

type Key = keyof typeof en;

const fr: Record<Key, string> = {
  loginTitle: 'Se connecter à OpenTV',
  username: "Nom d'utilisateur",
  password: 'Mot de passe',
  signIn: 'Se connecter',
  sso: "Continuer avec l'authentification unique",
  noMethods: "Aucune méthode de connexion n'est configurée. Contactez l'administrateur du serveur.",
  pending: "Votre compte d'authentification unique attend l'approbation d'un administrateur.",
  oidcError: "L'authentification unique n'a pas pu aboutir. Réessayez.",
  challengeInvalid: "Ce défi d'authentification a expiré ou a déjà été utilisé. Recommencez.",
  rateLimited: 'Trop de tentatives. Patientez un instant puis réessayez.',
  setupTitle: 'Créer le premier administrateur',
  setupToken: "Jeton d'initialisation",
  displayName: 'Nom affiché',
  createAdmin: "Créer l'administrateur",
  activateTitle: 'Activer votre compte',
  activationToken: "Jeton d'activation",
  choosePassword: 'Choisir un mot de passe',
  passwordHint: 'Utilisez au moins 12 caractères.',
  continue: 'Continuer',
  totpTitle: "Configurer une application d'authentification",
  totpBody: 'Scannez ce QR code ou saisissez le secret manuellement, puis entrez le code à six chiffres.',
  totpCode: 'Code à 6 chiffres',
  secret: 'Secret manuel',
  verify: 'Vérifier',
  mfaTitle: 'Authentification à deux facteurs',
  mfaBody: 'Effectuez une seconde étape pour terminer la connexion.',
  useAuthenticator: "Utiliser un code d'authentification",
  useSecurityKey: 'Utiliser une clé de sécurité',
  useRecovery: 'Utiliser un code de récupération',
  recoveryCode: 'Code de récupération',
  securityKeyLabel: 'Nom de la clé de sécurité',
  securityKeyDefault: 'Clé de sécurité',
  securityKeyUnavailable: 'Les clés de sécurité sont indisponibles dans ce navigateur ou ce contexte non sécurisé.',
  securityKeyOptionsInvalid: 'Les options de clé de sécurité renvoyées par le serveur sont invalides.',
  securityKeyRegistrationCancelled: "L'enregistrement de la clé de sécurité a été annulé.",
  securityKeyRequestCancelled: 'La demande de clé de sécurité a été annulée.',
  recentAuthRequired: 'Une authentification récente est requise.',
  securityTitle: 'Sécurité du compte',
  securitySubtitle: 'Gérez votre mot de passe, vos clés, vos codes de récupération et vos sessions.',
  changePassword: 'Modifier le mot de passe',
  newPassword: 'Nouveau mot de passe',
  passwordChanged: 'Mot de passe modifié.',
  addSecurityKey: 'Ajouter une clé de sécurité',
  securityKeyAdded: 'Clé de sécurité ajoutée.',
  recoveryTitle: 'Enregistrez vos codes de récupération',
  recoveryBody: "Chaque code ne peut être utilisé qu'une fois. Conservez-les en lieu sûr : ils ne seront plus affichés.",
  regenerate: 'Générer de nouveaux codes',
  copy: 'Copier',
  download: 'Télécharger',
  copied: 'Copié.',
  copyFailed: 'Impossible de copier les codes. Sélectionnez-les et copiez-les manuellement.',
  downloadFailed: 'Impossible de télécharger les codes. Sélectionnez-les et enregistrez-les manuellement.',
  savedCodes: "J'ai enregistré ces codes",
  currentLogout: 'Déconnecter cette session',
  allLogout: 'Déconnecter tous les appareils',
  cancelled: 'Le navigateur a annulé la demande de clé de sécurité.',
  genericError: 'Une erreur est survenue. Réessayez.',
  challengeMissing: "Le défi d'authentification est invalide.",
  authIncomplete: "L'authentification n'est pas terminée.",
  serviceUnavailable: "Le service d'authentification est indisponible.",
  retry: 'Réessayer',
  backToLogin: 'Retour à la connexion',
};

export const authText = (key: Key): string => (getLocale() === 'fr' ? fr[key] : en[key]);
