import { getLocale } from '../i18n';

const en = {
  loginTitle: 'Sign in',
  loginSubtitle: 'Use your OpenTV account to continue.',
  browserLinkLoginSubtitle: 'Sign in to finish linking the OpenTV app on this device.',
  username: 'Username',
  password: 'Password',
  signIn: 'Sign in',
  sso: 'Continue with single sign-on',
  or: 'or',
  noMethods: 'No sign-in method is configured. Contact the server administrator.',
  pending: 'Your single sign-on account is waiting for administrator approval.',
  oidcError: 'Single sign-on could not be completed. Please try again.',
  challengeInvalid: 'This authentication challenge expired or was already used. Start again.',
  challengeExpiredTitle: 'This sign-in step expired',
  challengeExpiredBody: 'Security checks are short-lived. Start again to get a fresh one.',
  startAgain: 'Start again',
  rateLimited: 'Too many attempts. Wait a moment and try again.',
  invalidCredentials: 'Those sign-in details were not accepted.',
  sessionEnded: 'Your session has ended. Sign in again.',
  haveToken: 'Received an activation token?',
  activateAccount: 'Activate an account',
  bootstrapCta: 'Create the first administrator',
  bootstrapCtaSub: 'This server has no account yet. You will need the bootstrap token from its log.',
  bootstrapDone: 'Administrator created',
  linkQrFailed: 'This device could not draw the sign-in code.',
  setupEyebrow: 'First run',
  setupTitle: 'Create the first administrator',
  setupSubtitle: 'This server has no accounts yet. The bootstrap token is printed in the server log.',
  setupToken: 'Bootstrap token',
  setupDone: 'This server already has an administrator. Sign in instead.',
  displayName: 'Display name',
  createAdmin: 'Create administrator',
  activateEyebrow: 'Welcome',
  activateTitle: 'Activate your account',
  activateSubtitle: 'Enter the token you were given, then choose a password.',
  activationToken: 'Activation token',
  choosePassword: 'Choose password',
  passwordHint: 'Use at least 12 characters.',
  continue: 'Continue',
  working: 'Working…',
  back: 'Back',
  mfaEyebrow: 'Security check',
  mfaTitle: 'Two-factor authentication',
  mfaBody: 'Confirm it is you with a second step.',
  enrollEyebrow: 'One more step',
  enrollTitle: 'Add a second step',
  enrollBody: 'Two-factor authentication protects this account before you continue.',
  useAuthenticator: 'Authenticator app',
  authenticatorSub: 'A six-digit code that changes every 30 seconds.',
  useSecurityKey: 'Security key',
  securityKeySub: 'A passkey, phone or hardware key.',
  useRecovery: 'Recovery code',
  recoverySub: 'One of the backup codes you saved.',
  totpTitle: 'Set up your authenticator',
  totpBody: 'Scan the QR code with your authenticator app, then enter the code it shows.',
  totpCodeTitle: 'Authenticator code',
  totpCodeBody: 'Enter the six-digit code from your app.',
  totpCode: '6-digit code',
  secret: 'Manual setup key',
  copySecret: 'Copy setup key',
  verify: 'Verify',
  recoveryStepTitle: 'Recovery code',
  recoveryStepBody: 'Enter one of the codes you saved. Each code works once.',
  recoveryCode: 'Recovery code',
  securityKeyStepTitle: 'Security key',
  securityKeyRegisterBody: 'Name this key, then follow your browser prompt to register it.',
  registerSecurityKey: 'Register this key',
  securityKeyAuthBody: 'Follow your browser prompt to use your security key.',
  securityKeyLabel: 'Security key name',
  securityKeyUnavailable: 'Security keys are unavailable in this browser or insecure context.',
  noPasswordAccount: 'This account has no password - it signs in through your identity provider or a passkey - so an authenticator app and recovery codes cannot be used with it. A passkey can be added below.',
  passkeyAddressUnsupported: 'Passkeys need an HTTPS address with a host name. Open OpenTV on its domain, or ask an administrator to set OPENTV_PUBLIC_URL.',
  securityKeyOptionsInvalid: 'The security-key options returned by the server are invalid.',
  securityKeyRegistrationCancelled: 'The security-key registration was cancelled.',
  securityKeyRequestCancelled: 'The security-key request was cancelled.',
  recentAuthRequired: 'Recent authentication is required.',
  securityTitle: 'Account security',
  securitySubtitle: 'Password, keys, recovery codes and sessions.',
  passwordCard: 'Password',
  passwordCardBody: 'Change the password you use to sign in.',
  changePassword: 'Change password',
  newPassword: 'New password',
  passwordChanged: 'Password changed.',
  addSecurityKey: 'Add security key',
  securityKeyAdded: 'Security key added.',
  securityKeyReplacesRecovery: 'Adding a key issues new recovery codes. The ones you hold now will stop working.',
  recoveryReplaced: 'These replace your earlier recovery codes, which have stopped working.',
  recoveryCard: 'Recovery codes',
  recoveryCardBody: 'Generate a fresh set. Every earlier code stops working immediately.',
  regenerate: 'Generate new codes',
  recoveryRegenerated: 'New recovery codes generated.',
  sessionsCard: 'Sessions',
  sessionsCardBody: 'Sign out of this browser, or of every device signed in to this account.',
  allLogoutTitle: 'Sign out everywhere?',
  allLogoutBody: 'Every device signed in to this account is signed out, including this browser.',
  recoveryTitle: 'Save your recovery codes',
  recoveryBody: 'Each code can be used once. Store them somewhere safe; they will not be shown again.',
  copy: 'Copy',
  download: 'Download',
  copied: 'Copied.',
  copyFailed: 'Could not copy the codes. Select and copy them manually.',
  downloadFailed: 'Could not download the codes. Select and save them manually.',
  savedCodes: 'I have saved these codes',
  currentLogout: 'Sign out',
  allLogout: 'Sign out everywhere',
  cancelled: 'The prompt closed without a passkey or security key. It may have been dismissed, timed out, or had nothing to offer for this server.',
  genericError: 'Something went wrong. Try again.',
  challengeMissing: 'The authentication challenge is invalid.',
  authIncomplete: 'Authentication has not completed.',
  serviceUnavailableTitle: 'Cannot reach OpenTV',
  serviceUnavailable: 'The authentication service is unavailable.',
  retry: 'Retry',
  backToLogin: 'Back to sign in',
  usePasskey: 'Sign in with a passkey',
  passkeyUnavailable: 'This browser cannot use passkeys. Sign in another way.',
  useAnotherDevice: 'Sign in from another device',
  linkEyebrow: 'Link this device',
  linkTitle: 'Scan to sign in',
  linkBody: 'Scan it with your phone, then confirm there.',
  linkWaiting: 'Waiting for approval…',
  linkExpiredTitle: 'This code expired',
  linkExpiredBody: 'Codes are short-lived so an old screen cannot be approved later.',
  linkDeniedTitle: 'Request refused',
  linkDeniedBody: 'The other device turned this sign-in down.',
  linkNewCode: 'Show a new code',
  linkStartFailed: 'Could not start the sign-in request.',
  linkIncomplete: 'The request was approved but no session arrived. Show a new code and try again.',
  linkApproveTitle: 'Sign-in request',
  linkApproveSubtitle: 'A device is asking to sign in as you.',
  linkApproveIntro: 'Only approve a device you are standing in front of.',
  linkDeviceUnknown: 'Unnamed device',
  linkRequestedAt: 'Requested {date}',
  linkApprove: 'Approve',
  linkDeny: 'Refuse',
  linkApproved: 'Device signed in',
  linkApprovedBody: 'The other device is signing in now. You can close this page.',
  linkDeniedDone: 'Request refused',
  linkDeniedDoneBody: 'Nothing was signed in.',
  linkNotFound: 'That request is unknown or has expired. Scan a fresh code on the device.',
  linkScannedTitle: 'Almost there',
  linkScannedBody: 'Confirm the sign-in on your phone to finish.',
  linkConfirmOnPhone: 'Waiting for your confirmation…',
  linkQuestion: 'Sign this device in as {account}?',
  linkScanFirstTitle: 'Nothing to approve',
  linkScanFirstBody: 'Open this page by scanning the code shown on the other device.',
  authenticatorCard: 'Authenticator app',
  authenticatorCardBody: 'A six-digit code from an app, as a second step after your password.',
  authenticatorAdd: 'Set up authenticator app',
  authenticatorReady: 'Configured {date}',
  authenticatorAdded: 'Authenticator app added.',
  authenticatorExists: 'This account already has an authenticator app.',
  authenticatorRemove: 'Remove authenticator app',
  authenticatorRemoveTitle: 'Remove the authenticator app?',
  authenticatorRemoveBody: 'Codes from that app will stop working. You can set up a new app afterwards.',
  authenticatorRemoved: 'Authenticator app removed.',
  passkeysCard: 'Passkeys',
  passkeysCardBody: 'Sign in without a password on devices that hold one of these.',
  passkeyAdded: 'Added {date}',
  passkeyLastUsed: 'Last used {date}',
  passkeyNeverUsed: 'Never used',
  passkeySynced: 'Synced',
  passkeyRemove: 'Remove passkey',
  passkeyRemoved: 'Passkey removed.',
  passkeyRemoveTitle: 'Remove this passkey?',
  passkeyRemoveBody: 'Devices holding it will no longer be able to sign in with it.',
  passkeyLastFactor: 'This is the last factor left on this account. Add another method first.',
  noPasskeys: 'No passkeys yet.',
} as const;

type Key = keyof typeof en;

const fr: Record<Key, string> = {
  loginTitle: 'Connexion',
  loginSubtitle: 'Utilisez votre compte OpenTV pour continuer.',
  browserLinkLoginSubtitle: "Connectez-vous pour terminer l'association de l'application OpenTV sur cet appareil.",
  username: "Nom d'utilisateur",
  password: 'Mot de passe',
  signIn: 'Se connecter',
  sso: "Continuer avec l'authentification unique",
  or: 'ou',
  noMethods: "Aucune méthode de connexion n'est configurée. Contactez l'administrateur du serveur.",
  pending: "Votre compte d'authentification unique attend l'approbation d'un administrateur.",
  oidcError: "L'authentification unique n'a pas pu aboutir. Réessayez.",
  challengeInvalid: "Ce défi d'authentification a expiré ou a déjà été utilisé. Recommencez.",
  challengeExpiredTitle: 'Cette étape de connexion a expiré',
  challengeExpiredBody: 'Les vérifications de sécurité sont éphémères. Recommencez pour en obtenir une nouvelle.',
  startAgain: 'Recommencer',
  rateLimited: 'Trop de tentatives. Patientez un instant puis réessayez.',
  invalidCredentials: "Ces identifiants n'ont pas été acceptés.",
  sessionEnded: 'Votre session est terminée. Reconnectez-vous.',
  haveToken: "Vous avez reçu un jeton d'activation ?",
  activateAccount: 'Activer un compte',
  bootstrapCta: 'Créer le premier administrateur',
  bootstrapCtaSub: "Ce serveur n'a encore aucun compte. Le jeton d'initialisation figure dans son journal.",
  bootstrapDone: 'Administrateur créé',
  linkQrFailed: "Cet appareil n'a pas pu afficher le code de connexion.",
  setupEyebrow: 'Première utilisation',
  setupTitle: 'Créer le premier administrateur',
  setupSubtitle: "Ce serveur n'a encore aucun compte. Le jeton d'initialisation est affiché dans le journal du serveur.",
  setupToken: "Jeton d'initialisation",
  setupDone: 'Ce serveur a déjà un administrateur. Connectez-vous.',
  displayName: 'Nom affiché',
  createAdmin: "Créer l'administrateur",
  activateEyebrow: 'Bienvenue',
  activateTitle: 'Activer votre compte',
  activateSubtitle: "Saisissez le jeton qui vous a été remis, puis choisissez un mot de passe.",
  activationToken: "Jeton d'activation",
  choosePassword: 'Choisir un mot de passe',
  passwordHint: 'Utilisez au moins 12 caractères.',
  continue: 'Continuer',
  working: 'En cours…',
  back: 'Retour',
  mfaEyebrow: 'Vérification',
  mfaTitle: 'Authentification à deux facteurs',
  mfaBody: "Confirmez qu'il s'agit bien de vous avec une seconde étape.",
  enrollEyebrow: 'Encore une étape',
  enrollTitle: 'Ajouter une seconde étape',
  enrollBody: "L'authentification à deux facteurs protège ce compte avant de continuer.",
  useAuthenticator: "Application d'authentification",
  authenticatorSub: 'Un code à six chiffres renouvelé toutes les 30 secondes.',
  useSecurityKey: 'Clé de sécurité',
  securityKeySub: 'Une passkey, un téléphone ou une clé matérielle.',
  useRecovery: 'Code de récupération',
  recoverySub: 'Un des codes de secours que vous avez enregistrés.',
  totpTitle: "Configurer votre application d'authentification",
  totpBody: "Scannez le QR code avec votre application, puis saisissez le code affiché.",
  totpCodeTitle: "Code d'authentification",
  totpCodeBody: 'Saisissez le code à six chiffres de votre application.',
  totpCode: 'Code à 6 chiffres',
  secret: 'Clé de configuration manuelle',
  copySecret: 'Copier la clé',
  verify: 'Vérifier',
  recoveryStepTitle: 'Code de récupération',
  recoveryStepBody: "Saisissez un des codes enregistrés. Chaque code ne sert qu'une fois.",
  recoveryCode: 'Code de récupération',
  securityKeyStepTitle: 'Clé de sécurité',
  securityKeyRegisterBody: "Nommez cette clé, puis suivez l'invite de votre navigateur pour l'enregistrer.",
  registerSecurityKey: 'Enregistrer cette clé',
  securityKeyAuthBody: "Suivez l'invite de votre navigateur pour utiliser votre clé de sécurité.",
  securityKeyLabel: 'Nom de la clé de sécurité',
  securityKeyUnavailable: 'Les clés de sécurité sont indisponibles dans ce navigateur ou ce contexte non sécurisé.',
  noPasswordAccount: "Ce compte n'a pas de mot de passe - il se connecte via votre fournisseur d'identité ou une passkey - donc une application d'authentification et des codes de secours ne peuvent pas être utilisés. Une passkey peut être ajoutée ci-dessous.",
  passkeyAddressUnsupported: "Les passkeys exigent une adresse HTTPS avec un nom d'hôte. Ouvrez OpenTV sur son domaine, ou demandez à un administrateur de définir OPENTV_PUBLIC_URL.",
  securityKeyOptionsInvalid: 'Les options de clé de sécurité renvoyées par le serveur sont invalides.',
  securityKeyRegistrationCancelled: "L'enregistrement de la clé de sécurité a été annulé.",
  securityKeyRequestCancelled: 'La demande de clé de sécurité a été annulée.',
  recentAuthRequired: 'Une authentification récente est requise.',
  securityTitle: 'Sécurité du compte',
  securitySubtitle: 'Mot de passe, clés, codes de récupération et sessions.',
  passwordCard: 'Mot de passe',
  passwordCardBody: 'Modifiez le mot de passe utilisé pour vous connecter.',
  changePassword: 'Modifier le mot de passe',
  newPassword: 'Nouveau mot de passe',
  passwordChanged: 'Mot de passe modifié.',
  addSecurityKey: 'Ajouter une clé',
  securityKeyAdded: 'Clé de sécurité ajoutée.',
  securityKeyReplacesRecovery: 'Ajouter une clé génère de nouveaux codes de récupération. Ceux que vous détenez cesseront de fonctionner.',
  recoveryReplaced: 'Ces codes remplacent les précédents, qui ne fonctionnent plus.',
  recoveryCard: 'Codes de récupération',
  recoveryCardBody: 'Générez une nouvelle série. Les anciens codes cessent aussitôt de fonctionner.',
  regenerate: 'Générer de nouveaux codes',
  recoveryRegenerated: 'Nouveaux codes de récupération générés.',
  sessionsCard: 'Sessions',
  sessionsCardBody: 'Déconnectez ce navigateur, ou tous les appareils connectés à ce compte.',
  allLogoutTitle: 'Tout déconnecter ?',
  allLogoutBody: 'Tous les appareils connectés à ce compte sont déconnectés, y compris ce navigateur.',
  recoveryTitle: 'Enregistrez vos codes de récupération',
  recoveryBody: "Chaque code ne peut être utilisé qu'une fois. Conservez-les en lieu sûr : ils ne seront plus affichés.",
  copy: 'Copier',
  download: 'Télécharger',
  copied: 'Copié.',
  copyFailed: 'Impossible de copier les codes. Sélectionnez-les et copiez-les manuellement.',
  downloadFailed: 'Impossible de télécharger les codes. Sélectionnez-les et enregistrez-les manuellement.',
  savedCodes: "J'ai enregistré ces codes",
  currentLogout: 'Se déconnecter',
  allLogout: 'Déconnecter tous les appareils',
  cancelled: "La demande s'est terminée sans passkey ni clé de sécurité. Elle a peut-être été annulée, a expiré, ou n'avait rien à proposer pour ce serveur.",
  genericError: 'Une erreur est survenue. Réessayez.',
  challengeMissing: "Le défi d'authentification est invalide.",
  authIncomplete: "L'authentification n'est pas terminée.",
  serviceUnavailableTitle: 'OpenTV est injoignable',
  serviceUnavailable: "Le service d'authentification est indisponible.",
  retry: 'Réessayer',
  backToLogin: 'Retour à la connexion',
  usePasskey: 'Se connecter avec une passkey',
  passkeyUnavailable: 'Ce navigateur ne gère pas les passkeys. Connectez-vous autrement.',
  useAnotherDevice: 'Se connecter depuis un autre appareil',
  linkEyebrow: 'Associer cet appareil',
  linkTitle: 'Scannez pour vous connecter',
  linkBody: 'Scannez-le avec votre téléphone, puis confirmez sur celui-ci.',
  linkWaiting: 'En attente d’approbation…',
  linkExpiredTitle: 'Ce code a expiré',
  linkExpiredBody: "Les codes sont éphémères pour qu'un ancien écran ne puisse pas être approuvé plus tard.",
  linkDeniedTitle: 'Demande refusée',
  linkDeniedBody: "L'autre appareil a refusé cette connexion.",
  linkNewCode: 'Afficher un nouveau code',
  linkStartFailed: "Impossible de démarrer la demande de connexion.",
  linkIncomplete: "La demande a été approuvée mais aucune session n'est arrivée. Affichez un nouveau code puis réessayez.",
  linkApproveTitle: 'Demande de connexion',
  linkApproveSubtitle: 'Un appareil demande à se connecter avec votre compte.',
  linkApproveIntro: "N'approuvez qu'un appareil devant lequel vous vous trouvez.",
  linkDeviceUnknown: 'Appareil sans nom',
  linkRequestedAt: 'Demandé le {date}',
  linkApprove: 'Approuver',
  linkDeny: 'Refuser',
  linkApproved: 'Appareil connecté',
  linkApprovedBody: "L'autre appareil se connecte. Vous pouvez fermer cette page.",
  linkDeniedDone: 'Demande refusée',
  linkDeniedDoneBody: "Aucune connexion n'a été établie.",
  linkNotFound: 'Cette demande est inconnue ou a expiré. Scannez un nouveau code sur l’appareil.',
  linkScannedTitle: 'Presque terminé',
  linkScannedBody: 'Confirmez la connexion sur votre téléphone pour terminer.',
  linkConfirmOnPhone: 'En attente de votre confirmation…',
  linkQuestion: 'Connecter cet appareil en tant que {account} ?',
  linkScanFirstTitle: 'Rien à approuver',
  linkScanFirstBody: "Ouvrez cette page en scannant le code affiché sur l'autre appareil.",
  authenticatorCard: "Application d'authentification",
  authenticatorCardBody: 'Un code à six chiffres généré par une application, après votre mot de passe.',
  authenticatorAdd: "Configurer l'application",
  authenticatorReady: 'Configurée le {date}',
  authenticatorAdded: "Application d'authentification ajoutée.",
  authenticatorExists: "Ce compte possède déjà une application d'authentification.",
  authenticatorRemove: "Supprimer l'application",
  authenticatorRemoveTitle: "Supprimer l'application d'authentification ?",
  authenticatorRemoveBody: "Les codes de cette application cesseront de fonctionner. Vous pourrez en configurer une autre ensuite.",
  authenticatorRemoved: "Application d'authentification supprimée.",
  passkeysCard: 'Passkeys',
  passkeysCardBody: 'Connectez-vous sans mot de passe sur les appareils qui en détiennent une.',
  passkeyAdded: 'Ajoutée le {date}',
  passkeyLastUsed: 'Dernière utilisation {date}',
  passkeyNeverUsed: 'Jamais utilisée',
  passkeySynced: 'Synchronisée',
  passkeyRemove: 'Supprimer la passkey',
  passkeyRemoved: 'Passkey supprimée.',
  passkeyRemoveTitle: 'Supprimer cette passkey ?',
  passkeyRemoveBody: 'Les appareils qui la détiennent ne pourront plus s’en servir pour se connecter.',
  passkeyLastFactor: 'C’est le dernier facteur de ce compte. Ajoutez-en un autre d’abord.',
  noPasskeys: 'Aucune passkey pour l’instant.',
};

export function authText(key: Key, values: Record<string, string | number> = {}): string {
  const template = getLocale() === 'fr' ? fr[key] : en[key];
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}
